services:
  db:
    image: mysql:8.0
    container_name: mjsec-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
      
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mjsec-network

  redis:
    image: redis:6-alpine
    container_name: mjsec-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mjsec-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mjsec-app
    ports:
      - "8080:8080"
    environment:
      # Database - application.yml에서 사용하는 변수명
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      # Gmail - application.yml에서 사용하는 변수명
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_PASSWORD}

      # JWT, Admin
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_NUMBER: ${ADMIN_NUMBER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
    depends_on:
      - db
      - redis
    networks:
      - mjsec-network

volumes:
  db_data:
  redis_data:

networks:
  mjsec-network:
    driver: bridge